# Generated by Django 5.0.1 on 2024-01-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0003_contact_info_rename_blog_cat_blog_category_blog_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscription_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
