# Generated by Django 5.0.1 on 2024-01-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0004_subscription_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription_info',
            old_name='u_email',
            new_name='s_email',
        ),
    ]
