# Generated by Django 5.0.1 on 2024-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0007_blog_post_blog_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_category',
            old_name='blog_Cat',
            new_name='blog_cat',
        ),
        migrations.RenameField(
            model_name='blog_post',
            old_name='blog_Cat',
            new_name='blog_cat',
        ),
    ]
