# Generated by Django 5.0.1 on 2024-02-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0008_rename_blog_cat_blog_category_blog_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='blog_likes',
            field=models.IntegerField(default=0),
        ),
    ]
