# Generated by Django 5.0.1 on 2024-02-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0009_blog_post_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='blog_likes',
        ),
        migrations.AddField(
            model_name='blog_post',
            name='like_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
