# Generated by Django 5.0.1 on 2024-02-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0010_remove_blog_post_blog_likes_blog_post_like_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblogs.blog_post')),
            ],
        ),
    ]
