# Generated by Django 5.0.1 on 2024-02-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0011_blog_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_comments',
            new_name='blog_comment',
        ),
    ]
