# Generated by Django 5.0.1 on 2024-02-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0012_rename_blog_comments_blog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_comment',
            name='blog_id',
        ),
    ]
