# Generated by Django 5.0.1 on 2024-02-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0015_rename_comment_blog_comment_u_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_comment',
            old_name='u_comment',
            new_name='comment',
        ),
    ]
