# Generated by Django 5.0.1 on 2024-02-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0016_rename_u_comment_blog_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_comment', models.CharField(max_length=500)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblogs.blog_post')),
            ],
        ),
        migrations.DeleteModel(
            name='blog_comment',
        ),
    ]
