# Generated by Django 5.0.1 on 2024-02-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0018_rename_blog_comments_blog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='blog_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myblogs.blog_category'),
            preserve_default=False,
        ),
    ]
