# Generated by Django 5.0.1 on 2024-02-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0019_blog_comment_blog_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_comment',
            name='blog_cat',
        ),
    ]
